import os
import re
import csv
import argparse
from collections import defaultdict


def generate_mapping_table(log_directory):
    """
    Scans all .txt files in a directory, extracts id-to-move mappings,
    and identifies any conflicts.

    Args:
        log_directory (str): The path to the directory containing the log files.

    Returns:
        dict: A dictionary where keys are move IDs and values are sets of
              all move strings found for that ID. e.g., {17: {'g2g4'}, 6: {'b7b6', 'f1c4'}}
    """
    # 第一次遇到一個新的 id 時，自動建立一個空集合
    mappings = defaultdict(set)
    pattern = re.compile(r"id: (\d+), move: (\S+)")

    print(f"[*] Starting to scan directory: {log_directory}")

    # 遍歷資料夾中的所有檔案和子資料夾
    for root, _, files in os.walk(log_directory):
        for filename in files:
            if filename.endswith(".txt"):
                file_path = os.path.join(root, filename)
                print(f"  - Processing file: {filename}")
                with open(file_path, 'r', encoding='utf-8') as f:
                    for line in f:
                        match = pattern.search(line)
                        if match:
                            # 抓取到的 id 是字串，需要轉換成整數
                            move_id = int(match.group(1))
                            move_string = match.group(2)
                            # 將 mapping 加入到集合中，集合會自動處理重複的項目
                            mappings[move_id].add(move_string)
    print("[*] Scan complete.")
    return mappings


def write_to_csv(mappings, output_file):
    """
    Writes the final mapping table to a CSV file, highlighting any conflicts.

    Args:
        mappings (dict): The dictionary generated by generate_mapping_table.
        output_file (str): The path for the output CSV file.
    """
    print(f"[*] Writing mapping table to: {output_file}")
    with open(output_file, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        # 寫入 CSV 的標頭
        writer.writerow(['ID', 'MoveString', 'Status'])
        # 根據 id 進行排序
        sorted_ids = sorted(mappings.keys())
        conflict_count = 0
        for move_id in sorted_ids:
            move_set = mappings[move_id]
            # 檢查同一個 id 是否對應到多個不同的 move string
            if len(move_set) > 1:
                status = 'CONFLICT'
                # 將所有衝突的 string 用 " | " 連接起來
                display_string = " | ".join(sorted(list(move_set)))
                conflict_count += 1
            elif len(move_set) == 1:
                status = 'OK'
                # 從集合中取出唯一的元素
                display_string = move_set.pop()
            else:
                status = 'EMPTY'
                display_string = ''
            writer.writerow([move_id, display_string, status])
    print("[+] Done!")
    if conflict_count > 0:
        print(f"[!] Warning: Found {conflict_count} conflicting IDs. Check the CSV for details.")


def main():
    """Main function to parse arguments and run the script."""
    parser = argparse.ArgumentParser(
        description="Scans chess environment log files to create an ID-to-MoveString mapping table.",
        formatter_class=argparse.RawTextHelpFormatter
    )
    parser.add_argument(
        '-i', '--input-dir',
        default='env_test_output',
        help="Directory containing the .txt log files.\n(default: env_test_output)"
    )
    parser.add_argument(
        '-o', '--output-file',
        default='mapping_table.csv',
        help="Name of the output CSV file.\n(default: mapping_table.csv)"
    )
    args = parser.parse_args()

    mappings = generate_mapping_table(args.input_dir)
    if not mappings:
        print("[!] No valid 'id: ..., move: ...' lines found in any .txt files. Aborting.")
        return
    write_to_csv(mappings, args.output_file)


if __name__ == '__main__':
    main()
